# LBW Wizard - perfil de configuracion (sin contraseñas ni tokens)
# https://github.com/NedualV/lbw-wizard
VERSION=3.2
SAVED=2026-10-07 10:31
IDENT=Balanceador
MODE=lb
NWAN=2
CLASSIFIER=both-addresses
ROLE=balancer
LANMODE=existing
LANCREATE=n
LANIFS=ether5
LANNETS=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
LANPORTS=
LANGW=
LANPOOL=
LINKMODE=auto
LINKNET=10.255.255.0/30
BALIP=10.255.255.1
DOWNGW=10.255.255.2
CLIENTNETS=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
UPIF=ether1
LINKDHCP=si
DNS=1.1.1.1,8.8.8.8
DNSREMOTE=keep
MSSCLAMP=s
PROTECTWAN=s
HARDEN=s
MGMTNETS=10.255.255.0/30,172.16.100.0/24
PIN=n
DISKLOG=s
NTPSET=s
TZNAME=America/Santo_Domingo
TGENABLE=n
TGCHAT=
ROLLBACK_MIN=10
WNAME_1=ISP1
WIFBASE_1=ether1
WTYPE_1=dhcp
WVLAN_1=0
WADDR_1=
WGW_1=
WUSER_1=
WSPEED_1=100
WPIN_1=
WNAME_2=ISP2
WIFBASE_2=ether2
WTYPE_2=dhcp
WVLAN_2=0
WADDR_2=
WGW_2=
WUSER_2=
WSPEED_2=100
WPIN_2=
